#!/usr/bin/env bash

# Get the latest Git tag
latest_tag=$(git tag --sort=committerdate | rg '^github-v[\d]+\.[\d]+\.[\d]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "No tags found"
    exit 1
fi
echo "Latest tag: $latest_tag"

# Update latest tag
git tag -d latest
git push origin :refs/tags/latest
git tag -a latest $latest_tag -m "Update latest to $latest_tag"
git push origin latest